nover/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'nover'
urlpatterns = [
    path('',views.choice,name='nover'),
    path('search_book',views.search_book,name = 'search_book'),
    path('search/',views.search,name='search'),
    path('search/<int:book_pk>/<int:book_id>/',views.book,name = 'book'),
    path('search/<int:book_pk>/<int:book_id>/<int:a>/',views.book,name = 'book_save'),
    path('search/<int:book_pk>/<int:book_id>/<int:chapter_id>.html/',views.chapter,
         name = 'chapter'),
    path('q_search/',views.q_search,name = 'q_search'),
    path('q_chapter/<book_id>', views.q_chapter, name='q_chapter'),
    path('q_content/<book_id>/<chapter_id>', views.q_content, name='q_content'),
]

search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'search'
urlpatterns = [
    path('',views.search,name='search'),
    path('下载文件/',views.load,name = 'load'),
]

xmly/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'xmly'
urlpatterns = [
    path('',views.search,name='xmly'),
    path('search_result/',views.search_result,name = 'search_result'),
    path('album/<int:ab_id>', views.album, name='album'),
    path('zhubo/<int:zhubo_id>', views.zhubo, name='zhubo'),
    path('album/<int:zb_album_id>', views.zb_album, name='zb_album'),

]

爬虫学习/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('nover/',include('nover.urls')),
    path('search/', include('search.urls')),
    path('xmly/', include('xmly.urls')),
    path('admin/', admin.site.urls),
]

nover/models.py
from django.db import models

# Create your models here.

class BookName(models.Model):
    bookname = models.CharField(max_length = 20)
    bookauthor = models.CharField(max_length = 20,null = True,blank = True)
    def __str__(self):
        return self.bookname
    
class BookSpider(models.Model):
    bookname = models.ForeignKey(BookName,on_delete = models.CASCADE,null = True)
    spider_id = models.IntegerField(default=0)
    bookspider = models.CharField(max_length = 10000)
    def __str__(self):
        return self.bookspider

class Content(models.Model):
    bookspider = models.ForeignKey(BookSpider,on_delete = models.CASCADE,null = True)
    content = models.CharField(max_length = 50000,null = True)
    def __str__(self):
        return self.content

class Poll(models.Model):
    name = models.CharField(max_length=20, unique=True)
    poll_num = models.IntegerField(default=0)
    def __str__(self):
        return self.poll_num

search/models.py
from django.db import models
# Create your models here.
class Collect(models.Model):
    error_id = models.CharField(max_length=20)
    error_type = models.CharField(max_length=200, null=True, blank=True)
    error_index = models.CharField(max_length=2000, null=True, blank=True)
    def __str__(self):
        return self.error_type

nover/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .x23uscom import *
from django.urls import reverse
from .qidian import *

# Create your views here.
def choice(request):
    context = {}
    return render(request, 'nover/choice.html', context)

def search_book(request):
    context = {}
    return render(request,'nover/search_book.html',context)
    
def search(request):
    key_word = request.GET['key_word']
    res_obj = X23usCom(key_word)
    test = res_obj.index()
    if isinstance(test,(dict,)):
        url = test['url']
        chapter = Spider(url)
        info = chapter.info(chapter_url = '<a class="read" href="https://www.x23us.com/html/(.*?)" title=".*?">章节列表</a>')
        print(info)
        arg = info['chapter_url'][0].split('/')
        print(arg)
        return HttpResponseRedirect(reverse('nover:book',args=(arg[0],arg[1])))
    else:
        context = {'info':res_obj.info()}
        for i in res_obj.info().keys():
            try:
                Poll.objects.create(name=i,poll_num = 0)
            except:
                pass
        return render(request,'nover/search.html',context)

def book(request,book_pk,book_id,a = None):
    url = 'https://www.x23us.com/html/{}/{}/'.format(book_pk,book_id)
    book_name = '<meta name="og:novel:book_name" content="(.*?)"/>'
    book_author = '<meta name="og:novel:author" content="(.*?)"/>'
    book_info = '<td class="L"><a href="(.*?)">(.*?)</a></td>'
    xx = Spider(url)
    info_list = xx.info(book_name = book_name,book_author = book_author,book_info = book_info,)
    info_list['book_pk']=book_pk
    info_list['book_id']=book_id
    try:
        votes = Poll.objects.get(name = info_list['book_name'][0])
    except:
        pass
    else:
        votes.poll_num += 1
        votes.save()
        if votes.poll_num > 10:
            try:
                BookName.objects.get(bookname=info_list['book_name'][0],
                                     bookauthor=info_list['book_author'][0])
            except:
                book = BookName.objects.create(bookname=info_list['book_name'][0],
                                               bookauthor=info_list['book_author'][0])
                # print(info_list['book_info'])
                # num = len(info_list['book_info'])//10+1
                x = XiaoShuo(url=url, info_list=info_list, book=book)
                x.start()
                x.join()
                print('完毕！')
    if a == None:
        return render(request,'nover/book.html',context=info_list)
    else:
        try:
            book = BookName.objects.get(bookname = info_list['book_name'][0],
                                        bookauthor = info_list['book_author'][0])
        except:
            book = BookName.objects.create(bookname=info_list['book_name'][0],
                                           bookauthor=info_list['book_author'][0])
            #print(info_list['book_info'])
            num = len(info_list['book_info'])//10+1
            pool = []
            for n in range(num):
                pool.append(XiaoShuo(url = url,info_list = info_list,book = book))
            for x in pool:
                x.start()
                print('\n')
            for i in pool:
                i.join()
            print('完毕！')
            chapter_list = book.bookspider_set.all()
            #print(chapter_list)
            for chapter in chapter_list:
                chapter_content = chapter.content_set.all()
                with open(r'nover/save-content/书名：' + info_list['book_name'][0] + '-' + '作者：' +
                info_list['book_author'][0] + '.txt', 'a') as f:
                    f.write('\n\n')
                    f.write(chapter.bookspider)
                    f.write('\n\n')
                    f.write(chapter_content)
            return render(request, 'nover/save.html', context={})
        else:
            chapter_list = book.bookspider_set.order_by('spider_id')
            #print(chapter_list)
            for chapter in chapter_list:
                #print(chapter)
                chapter_content = Content.objects.get(bookspider = chapter)
                print(chapter_content.content)
                with open(r'nover/save-content/书名：' + info_list['book_name'][0] + '-' + '作者：' +
                          info_list['book_author'][0] + '.txt', 'a') as f:
                    f.write('\n\n')
                    f.write(chapter.bookspider)
                    f.write('\n\n')
                    f.write(chapter_content.content)
            return render(request, 'nover/save.html', context={})

def chapter(request,book_pk,book_id,chapter_id):
    url = 'https://www.x23us.com/html/{}/{}/{}.html'.format(book_pk,book_id,chapter_id)
    chapter_title = '<title>(.*?)</title>'
    chapter_content = '<dd id="contents">(.*)'
    previou_page = '<dd id="footlink"><a href="/html/(.*?)">上一页</a>' \
                   '<a href="/html/(.*?)" title=".*?">返回章节列表</a>' \
                   '<a href="/html/(.*?)">下一页</a></dd>'
    #next_page = '<a href="(.*?)">下一页</a>'
    x = Spider(url)
    info_list = x.info(chapter_title = chapter_title,
                       chapter_content = chapter_content,
                       previou_page = previou_page,
                       )

    return render(request,'nover/chapter.html',context = info_list)

def q_search(request):
    book_key = request.GET['book_key']
    book_list = QiDian_free().quanmian_book(book_key)['shuming']
    context = {'book':book_list}
    return render(request, 'nover/q_search.html', context)

def q_chapter(request,book_id):
    print(book_id)
    chapter_dict = QiDian_free().quanmian_chapter(book_id)
    book_page = QiDian_free().quanmian_page(chapter_dict['chapter'][0][0])
    context = {'book_name':book_page[1][1],'book_author':book_page[3],'chapter':chapter_dict}
    return render(request, 'nover/q_chapter.html', context)

def q_content(request,book_id,chapter_id):
    print(book_id)
    print(chapter_id)
    chapter_dict = QiDian_free().quanmian_chapter(book_id)['chapter'][int(chapter_id)-1]
    content = QiDian_free().quanmian_content(chapter_dict[0])
    context = content
    context['spage'] = int(chapter_id)-1
    context['xpage'] = int(chapter_id)+1
    context['book_id'] = book_id
    return render(request, 'nover/q_content.html', context)
'''
    except:
        return HttpResponseRedirect(reverse('nover:q_chapter',args=(book_id,)))
'''


























































































    

    

    

    

search/views.py
from django.shortcuts import render
from .xunlei import *
from .models import *
import sys,os

# Create your views here.
def search(request):
    context = {}
    return render(request,'search/search.html',context)

def load(request):
    url = request.GET['content_url']
    name = request.GET['name_g']
    print(name)
    run_save(url,name)
    context = {}
    return render(request,'search/load.html',context)

nover/templates/nover/book.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
          background-size: 100%;
          background-color: white;
          margin: 120px;
          color: #337ab7;
          font-family:"华文行楷";
          font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }
        .im{
            height: 70px;
        }
  </style>

</head>
<body>
    <div class="container">
		<div class="row">
			<div class="col-md-12 tabbable" id="tabs-142121">
				<h1>{{book_name.0}}</h1><br>
			</div>
			<div class="col-md-6 tabbable" id="tabs-142121">
				<p>作者：{{book_author.0}}<br></p><br>
			</div>
			<div class="col-md-6 tabbable" id="tabs-142121">
				<p><a href="{%url 'nover:book_save' book_pk book_id 7%}">TXT下载本书</a></p><br>
			</div>
		</div>
        <div class="row">
			{%for i in book_info%}
            <div class="col-md-6 tabbable im" id="tabs-142121">
                <a href ='{{i.0}}'>{{i.1}}</a><br>
                <hr />
            </div>
			{%endfor%}
        </div>
        <footer class="footer">
        <p class="foot">&copy; &copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

nover/templates/nover/choice.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{%static 'nover/image/ti1.ico'%}">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
          background-size: cover;
          background-color: white;
          color: #337ab7;
          margin: 220px;
          font-family:"华文行楷";
          font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }
  </style>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 tabbable" id="tabs-142121">
                 <div class="masthead">
                     <a href="{%url 'nover:search_book'%}">搜索免费小说</a>
                </div>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                 <div class="masthead">
                     <a href="{%url 'xmly:xmly'%}">搜索免费音频</a>
                </div>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                 <div class="masthead">
                     <a href="{%url 'search:search'%}">类迅雷下载</a>
                </div>
            </div>

        </div>
        <footer class="footer">
        <p class="foot">&copy; &copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

nover/templates/nover/q_chapter.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
          background-size: 100%;
          background-color: white;
          margin: 120px;
          color: #337ab7;
          font-family:"华文行楷";
          font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }
        .im{
            height: 105px;
        }
  </style>

</head>
<body>
    <div class="container">
		<div class="row">
			<div class="col-md-12 tabbable" id="tabs-142121">
				<h1>{{book_name}}</h1><br>
			</div>
			<div class="col-md-12 tabbable" id="tabs-142121">
				<p>作者：{{book_author}}<br></p><br>
			</div>
		</div>
        <div class="row">
			{%for i in chapter.chapter%}
            <div class="col-md-6 tabbable im" id="tabs-142121">
                <a href ='{%url "nover:q_content" chapter.book_id forloop.counter%}'>{{i.2}}<br>
                    {{i.1}}</a><br>
                <hr />
            </div>
			{%endfor%}
        </div>
        <footer class="footer">
        <p class="foot">&copy; &copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

nover/templates/nover/q_content.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
          background-size: 100%;
          background-color: white;
          color: #337ab7;
          font-family:"华文行楷";
          font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }
        body {
            margin: 80px;
        }
  </style>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 tabbable">
                <h1>{{chapter.0}}</h1><br>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_content' book_id spage%}">上一页</a>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_chapter' book_id%}">回到章节目录</a>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_content' book_id xpage%}">下一页</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 tabbable" id="tabs-142121">
                 <div class="masthead">
                     <br/>
                    {{content|safe}}
                     <hr>
                </div>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_content' book_id spage%}">上一页</a>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_chapter' book_id%}">回到章节目录</a>
            </div>
            <div class="col-md-4 tabbable" id="tabs-142121">
                <a href = "{%url 'nover:q_content' book_id xpage%}">下一页</a>
            </div>
        </div>
        <footer class="footer">
        <p class="foot">&copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

nover/templates/nover/q_search.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
		  background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
		  background-size: 100%;
		  background-color: white;
		  color: #337ab7;
		  margin: 220px;
          font-family:"华文行楷";
		  font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .tabbable{
            background: rgba(255,255,255,0.7);
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
		.tabbable {
            background: rgba(255,255,255,0.9);
        }
  </style>

</head>
<body>
    <div class="container">
        <div class="row">
			{%for i in book%}
            <div class="col-md-4 tabbable" id="tabs-142121">
					 <a href = "{%url 'nover:q_chapter' i.0%}"><p>
					 书名：{{i.1|safe}}<br>
					 作者：{{i.3}}<br>
					 </p></a>
					 <hr />
            </div>
			{%endfor%}
        </div>
        <footer class="footer">
        <p class="foot">&copy; &copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

nover/templates/nover/search_book.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="justified-nav.css" rel="stylesheet">
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800" );
          background-size: cover;
          background-color: white;
          color: #337ab7;
          margin: 220px;
          font-family:"华文行楷";
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .tabbable{
            background: rgba(255,255,255,0.7);
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }

  </style>

</head>
<body>
    <div class="container">
        <div class="row">

            <div class="col-md-2">
            </div>
            <div class="col-md-8" id="tabs-142121">
                <div class="tabbable" id="tabs-142713">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#panel-71949" data-toggle="tab" contenteditable="false" class="glyphicon glyphicon-education">智能搜1</a>
                        </li>
                        <li class="">
                            <a href="#panel-486460" data-toggle="tab" contenteditable="false" class="glyphicon glyphicon-education">智能搜2</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="panel-71949">
                             <form action="{%url 'nover:search'%}" method="get">
                            {% csrf_token %}
                            <h3>输入要搜索的书名1：<input type="text" name="key_word" placeholder="输入关键字">
                                <input type="submit" value="开始搜索"></h3>

                            </form>
                        </div>
                        <div class="tab-pane" id="panel-486460">
                             <form action="{%url 'nover:q_search'%}" method="get">
                            {% csrf_token %}
                            <h3>输入要搜索的书名2：<input type="text" name="book_key" placeholder="输入关键字">
                                <input type="submit" value="开始搜索"></h3>
                            </form>
                        </div>
            </div>
            <div class="col-md-2">
            </div>
        </div>
        <footer class="footer">
        <p class="foot">&copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>