search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'search'
urlpatterns = [
    path('',views.search,name='search'),
    path('下载文件/',views.load,name = 'load'),
]

xmly/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'xmly'
urlpatterns = [
    path('',views.search,name='xmly'),
    path('search_result/',views.search_result,name = 'search_result'),
    path('album/<int:ab_id>', views.album, name='album'),
    path('zhubo/<int:zhubo_id>', views.zhubo, name='zhubo'),
    path('album/<int:zb_album_id>', views.zb_album, name='zb_album'),

]

爬虫学习/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('nover/',include('nover.urls')),
    path('search/', include('search.urls')),
    path('xmly/', include('xmly.urls')),
    path('admin/', admin.site.urls),
]

search/models.py
from django.db import models
# Create your models here.
class Collect(models.Model):
    error_id = models.CharField(max_length=20)
    error_type = models.CharField(max_length=200, null=True, blank=True)
    error_index = models.CharField(max_length=2000, null=True, blank=True)
    def __str__(self):
        return self.error_type

search/views.py
from django.shortcuts import render
from .xunlei import *
from .models import *
import sys,os

# Create your views here.
def search(request):
    context = {}
    return render(request,'search/search.html',context)

def load(request):
    url = request.GET['content_url']
    name = request.GET['name_g']
    print(name)
    run_save(url,name)
    context = {}
    return render(request,'search/load.html',context)

search/templates/search/load.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="justified-nav.css" rel="stylesheet">-->
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800");
          background-size: cover;
          background-color: white;
          color: #337ab7;
          margin: 220px;
          font-family:"华文行楷";
          font-size: 25px;
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
            padding-left: 6px;
        }
  </style>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 tabbable">
                <h1>下载完成</h1>
            </div>
            <div class="col-md-6 tabbable">
                <a href="{% url 'search:search'%}"><h1>继续下载</h1></a>
            </div>
        </div>
        <footer class="footer">
        <p class="foot">&copy; &copy; 智能爬，免费小说</p>
        </footer>
    </div>
<script type="text/javascript" src="{% static 'nover/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static 'nover/js/bootstrap.min.js' %}"></script>
</body>
</html>

search/templates/search/search.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>主页</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'nover/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="justified-nav.css" rel="stylesheet">
    <style type="text/css">
      body{
          background: url("http://bpic.588ku.com/back_pic/03/76/31/1557be98244b2bd.jpg!r850/fw/800" );
          background-size: cover;
          background-color: white;
          color: #337ab7;
          margin: 220px;
          font-family:"华文行楷";
        }
        /*.form-signin{background: rgba(255,255,255,0);width:320px;margin:120px auto;}*/
        /*阴影*/
        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}

        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        .tabbable{
            background: rgba(255,255,255,0.7);
        }
        .one{
            width: 100%;
            height: 450px;
            line-height: 450px;
        }
        .footer{

            position: fixed;
            left: 460px;
            bottom: 6px;
            background: rgba(255,255,255,0.7);
        }
        .footer .foot{
            margin: 0 auto;
        }
        .tabbable {
            background: rgba(255,255,255,0.9);
        }

  </style>

</head>
<body>
    <div class="container">
        <div class="row">

            <div class="col-md-2">
            </div>
            <div class="col-md-8 tabbable" id="tabs-142121">

                 <div class="masthead">
                     <form action="{%url 'search:load'%}" method="get">
                    {% csrf_token %}
                         <h3>输入要下载的链接：<input type="text" name="content_url" placeholder="输入链接"><br>
                             <h3>为它取名（包含扩展名）：<input type="text" name="name_g" placeholder="如：音乐.mp3">
                                 <input type="submit" value="开始下载" onclick="downLoad()"></h3>
                    </form>
                </div>
            </div>
            <div class="col-md-2">
            </div>
        </div>
        <footer class="footer">
        <p class="foot">&copy; 智能下载，快速免费</p>
        </footer>
    </div>
    <script type="text/javascript">
  		function downLoad() {
  			swal({
  				title: "正在下载",
				text: "2秒后自动关闭",
				timer: 2000,
				showConfirmButton: false,
  			});
  		}
    </script>
<script type="text/javascript" src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap部分： -->
<script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>